# Generated by Django 4.0.2 on 2022-03-21 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Measurements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.FloatField()),
                ('weight', models.FloatField()),
                ('blood_pressure', models.CharField(max_length=60)),
                ('glucose', models.FloatField()),
                ('cholesterol', models.FloatField()),
                ('iron', models.FloatField()),
                ('pulse', models.FloatField()),
                ('blood_oxygen', models.FloatField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapi.user')),
            ],
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('family_history', models.CharField(max_length=300)),
                ('medical_history', models.CharField(max_length=300)),
                ('medications', models.CharField(max_length=300)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapi.user')),
            ],
        ),
        migrations.CreateModel(
            name='Billing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('billing_address', models.CharField(max_length=60)),
                ('insurance_address', models.CharField(max_length=60)),
                ('member_id', models.CharField(max_length=60)),
                ('group_num', models.CharField(max_length=60)),
                ('insurance_plan_name', models.CharField(max_length=60)),
                ('insurance_plan_type', models.CharField(max_length=60)),
                ('holder_name', models.CharField(max_length=60)),
                ('holder_relation', models.CharField(max_length=60)),
                ('credit_card_num', models.CharField(max_length=60)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapi.user')),
            ],
        ),
    ]
